export const UPDATE_NAV_TEXT = 'UPDATE_NAV_TEXT'
export const UPDATE_NAV_TAB = 'UPDATE_NAV_TAB'

export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'

export const SINGLE_GET_POST = 'SINGLE_GET_POST'
export const SINGLE_GET_POST_SUCCESS = 'SINGLE_GET_POST_SUCCESS'
